AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'IQFieldBot - Personalized IQ Testing Chatbot API'

Parameters:
  Stage:
    Type: String
    Default: dev
    Description: Deployment stage
  
  OpenAIApiKey:
    Type: String
    NoEcho: true
    Description: OpenAI API Key for question generation

Globals:
  Function:
    Timeout: 30
    Runtime: python3.9
    Environment:
      Variables:
        STAGE: !Ref Stage
        OPENAI_API_KEY: !Ref OpenAIApiKey

Resources:
  # Lambda Function
  IQFieldBotAPI:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: main.lambda_handler
      Runtime: python3.9
      Events:
        ApiGateway:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref IQFieldBotApiGateway
        ApiGatewayRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
            RestApiId: !Ref IQFieldBotApiGateway

  # API Gateway
  IQFieldBotApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  # DynamoDB Tables
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'iqfieldbot-users-${Stage}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: email-index
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  SessionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'iqfieldbot-sessions-${Stage}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: user-id-index
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  QuestionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'iqfieldbot-questions-${Stage}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: field
          AttributeType: S
        - AttributeName: difficulty
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: field-difficulty-index
          KeySchema:
            - AttributeName: field
              KeyType: HASH
            - AttributeName: difficulty
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  # S3 Bucket for static files (optional)
  StaticFilesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'iqfieldbot-static-${Stage}-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  # IAM Role for Lambda
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource:
                  - !GetAtt UsersTable.Arn
                  - !GetAtt SessionsTable.Arn
                  - !GetAtt QuestionsTable.Arn
                  - !Sub '${UsersTable.Arn}/index/*'
                  - !Sub '${SessionsTable.Arn}/index/*'
                  - !Sub '${QuestionsTable.Arn}/index/*'

Outputs:
  ApiEndpoint:
    Description: 'API Gateway endpoint URL'
    Value: !Sub 'https://${IQFieldBotApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Stage}'
    Export:
      Name: !Sub '${AWS::StackName}-ApiEndpoint'
  
  StaticWebsiteURL:
    Description: 'S3 Static Website URL'
    Value: !GetAtt StaticFilesBucket.WebsiteURL
    Export:
      Name: !Sub '${AWS::StackName}-StaticWebsiteURL'